### ISSUE TITLE
Has this event ended?

### ISSUE THREAD

**Issue by HanbgCN** [OwshenNetwork/genesis#23]
Has this event ended?

**Comment by Tcmaruf** [comment]
Yes ser ended

**Comment by Bluebutter03** [comment]
I and my friend both did it a day before it ended but we were late to
submit the address on twitter due to electricity but we dropped it on the
#🌨️airdrop section on discord. Will we still be considered or that's it☹️?

**Comment by daunique** [comment]
just creating my wallet now will i still be elegible?
