### ISSUE TITLE
[Badge - EVM0x/Owshen Network Tutorial]

### ISSUE THREAD

**Issue by EVM0x** [OwshenNetwork/genesis#3]
Hi Owshen Team, I'm claiming my contributor badge for completing a developer tutorial/whitepaper

Github username : EVM0x
Tutorial/whitepaper : https://github.com/EVM0x/Owshen-Network
Request badge : Tutorial

It's a new experience and it's amazing to be one of the people who try your product in this phase of testnet. I hope this project can grow and achieve its goals on the day mainnet arrives.🔥🔥🔥

**Comment by Rashidxxx556** [comment]
./Owshen_v0.1.0_x86_64.AppImage wallet
