### ISSUE TITLE
Whitelisted wallet but 0 DIVE

### ISSUE THREAD

**Issue by Barliyer** [OwshenNetwork/genesis#35]
My Wallet OoOo3088b3af10d7a315760f3230a645d45025773b4e5c37ced9a2f22eb9506be9cca in white list but no distribute Dive token please help

![image](https://github.com/OwshenNetwork/genesis/assets/132816833/4d211f40-7360-46bc-830a-79762f1741c7)

**Comment by Swilla66** [comment]
I have the same issue.
