### ISSUE TITLE
[Badge - Contributor - mrvje]

### ISSUE THREAD

**Issue by mrvje** [OwshenNetwork/genesis#8]
Hi Owshen Team, I'm claiming my contributor badge for completing a developer tutorial

Github username : mrvje
Tutorial: https://medium.com/@vijaykumar1391997/simple-guide-to-run-owshen-network-node-0a262f2cba6b
Request badge : Tutorial

All the best for the future !!!
Thanks for the oppurtunity !

**Comment by cmnkobo** [comment]
Hi Owshen Team,

Submitting my contribution for my contributor badge for completing a developer tutorial.

Github Username: cmnkobo
Tutorial Repo: https://github.com/cmnkobo/genesis.git
Requested badge: Tutorial
Discord: chrismike1

Thank you
